---

name: 🐞 Bug report
description: Create a bug report to help us improve AdGuard VPN for iOS.
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Please answer the following questions for yourself before submitting an issue.
      description:
      options:
        - label: I am running the latest version
        - label: I checked the documentation and found no answer
        - label: I checked to make sure that this issue has not already been filed
    validations:
      required: true
  - type: input
    id: app_version
    attributes:
      label: AdGuard VPN version
      description: What version of our application are you running?
      placeholder: For example, 2.0.7(56)
    validations:
      required: true
  - type: dropdown
    id: tunnel_mode
    attributes:
      label: Operating mode
      description:
      multiple: false
      options:
        - General
        - Integrated
  - type: textarea
    attributes:
      label: Environment
      description: |
        Examples:
          - **OS**: 15.5
          - **Device and storage size**: iphone 12, 64GB
      value: |
          - OS:
          - Device and storage size:
      render: markdown
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Issue Details
      description: What happened?
      placeholder: Please describe the steps to reproduce the issue you've experienced.
    validations:
      required: true
  - type: textarea
    id: how_it_should_be
    attributes:
      label: Expected Behavior
      description:
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: screens
    attributes:
      label: Screenshots
      description: |
        If applicable add screenshots explaining your problem.
        You can drag and drop images or paste them from clipboard.
        Use `<details> </details>` tag to hide screenshots under the spoiler.
      placeholder: If applicable add screenshots explaining your problem.
      value: |
          <details><summary>Screenshot 1:</summary>

          <!-- paste screenshot here -->

          </details>
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description:
      placeholder: Add any other context about the problem here.
    validations:
      required: false